<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Copenhagen</name>
   <tag></tag>
   <elementGuidId>b93bf5f2-0228-4f4c-9681-0199c0096a49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DHTMLgoodies_dragableElement3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da38bea8-b896-4f83-8936-41bf03f3529d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBox</value>
      <webElementGuid>895ee3e8-dd48-4e09-81b4-24472cfe28eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DHTMLgoodies_dragableElement3</value>
      <webElementGuid>d3904136-77fd-4ed5-9664-c19ae4f95236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dragableelement</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>45c94469-6e4b-4588-9450-b7e01ffc5e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copenhagen</value>
      <webElementGuid>b079564a-c6ca-46e2-bbee-95d2e150795d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DHTMLgoodies_dragableElement3&quot;)</value>
      <webElementGuid>7091d5ab-3639-4eb0-9337-ede212666fa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='DHTMLgoodies_dragableElement3']</value>
      <webElementGuid>5c327b7c-462b-42d7-9684-dbe087caa97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropContent']/div[5]</value>
      <webElementGuid>b4d20a1e-e887-473b-9110-159e9936b4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Washington'])[1]/following::div[1]</value>
      <webElementGuid>de6eaa7f-0506-498f-8d89-9059c3890135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholm'])[2]/following::div[2]</value>
      <webElementGuid>2b76756b-1058-4adb-ae27-2938f73bf5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul'])[1]/preceding::div[1]</value>
      <webElementGuid>3f46b677-946d-46db-bf90-82888a4bf80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul'])[2]/preceding::div[2]</value>
      <webElementGuid>90201e4a-3507-453a-9fd8-8915164b1bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copenhagen']/parent::*</value>
      <webElementGuid>04578e42-e9ef-4329-8890-11b91c815137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]</value>
      <webElementGuid>57ef2091-04fc-4849-ab20-aecc5c2ff872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'DHTMLgoodies_dragableElement3' and (text() = 'Copenhagen' or . = 'Copenhagen')]</value>
      <webElementGuid>1eb39116-30f9-478b-8f44-fbfaa0d75de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
