<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Norway</name>
   <tag></tag>
   <elementGuidId>7023c6de-bb36-4265-abd8-bf9f5f295067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#box101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box101&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>758edaf1-6e90-459b-9af0-6c0cef7d52d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box101</value>
      <webElementGuid>fcceb9c9-a703-4f18-9d65-adbe330f99fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBoxRight</value>
      <webElementGuid>eefc55f5-c062-4ec4-93e8-1785174acd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Norway</value>
      <webElementGuid>a865a211-2b06-45bd-b68c-06e4a4297f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box101&quot;)</value>
      <webElementGuid>30e3c97a-dd9f-4380-8294-48ee4023b797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='box101']</value>
      <webElementGuid>0c8a8159-b693-4c72-8edf-1a353f5c87e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='countries']/div[3]</value>
      <webElementGuid>cad864c6-d5bf-4b4f-ab24-63b72e9317e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spain'])[1]/following::div[1]</value>
      <webElementGuid>5007bb19-092b-4af2-b3fa-eac079e98613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italy'])[1]/following::div[2]</value>
      <webElementGuid>ec5432e2-41d9-4c47-aad3-3454aa2a6e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denmark'])[1]/preceding::div[1]</value>
      <webElementGuid>366fd99f-a2a1-4676-8be5-80b39720dc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Korea'])[1]/preceding::div[2]</value>
      <webElementGuid>41a1a329-e7d0-43c1-b270-99d5661e1ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Norway']/parent::*</value>
      <webElementGuid>a766b10f-c1fc-408a-a218-c313518bc0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>f2d3e5d1-3bcd-4e10-b27a-c5137eb54943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box101' and (text() = 'Norway' or . = 'Norway')]</value>
      <webElementGuid>7476518c-bbd2-4b0c-801d-ba9505504e16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
