<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Oslo</name>
   <tag></tag>
   <elementGuidId>e3d7fcaa-a6d4-4d92-916c-62f49ae8f6a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DHTMLgoodies_dragableElement0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9bf20ab2-1912-4c8a-a14f-7b16fcceb86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBox</value>
      <webElementGuid>d2ddc23a-7627-439b-add3-9e9a9e873706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DHTMLgoodies_dragableElement0</value>
      <webElementGuid>2bc7b88c-f5cd-4b57-aa8b-507f32f74f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dragableelement</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>794e0b83-0d1a-41d6-9ef6-019022283855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oslo</value>
      <webElementGuid>2d55fd92-99c3-4c75-af08-1f193eba5db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DHTMLgoodies_dragableElement0&quot;)</value>
      <webElementGuid>6409f353-5663-44f4-b751-e19e3889c812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='DHTMLgoodies_dragableElement0']</value>
      <webElementGuid>a615aa87-6d9e-4ece-b3ae-c139b92bfcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropContent']/div</value>
      <webElementGuid>09189b2c-5198-4881-8d74-451c88f565f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capitals'])[1]/following::div[2]</value>
      <webElementGuid>7d67c626-edd1-49dd-a0cb-da1db323b499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and drop - demo 3'])[1]/following::div[4]</value>
      <webElementGuid>e9b9fc24-bb50-412e-9543-5265b370da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholm'])[1]/preceding::div[1]</value>
      <webElementGuid>c6ac560b-9248-4bdb-9975-db45aa513ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholm'])[2]/preceding::div[2]</value>
      <webElementGuid>3ccc0f8a-729b-4ac6-a9c0-ce3602b78963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oslo']/parent::*</value>
      <webElementGuid>a5abbfd8-ebf7-444b-bcaa-4cbbffe838d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>520dc738-0717-4ac7-a843-24f25cdcbf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'DHTMLgoodies_dragableElement0' and (text() = 'Oslo' or . = 'Oslo')]</value>
      <webElementGuid>f19863fd-4115-4318-aa79-ab7b6deb52a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
