<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Denmark</name>
   <tag></tag>
   <elementGuidId>e5225350-d467-4853-8c57-780c862508ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#box104</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box104&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22cf719d-2e2d-4d50-a6b9-85358c584f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box104</value>
      <webElementGuid>17493c65-c2f9-4afb-8c36-ecb443ff8208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBoxRight</value>
      <webElementGuid>46fb86f8-8259-427f-a0fb-c58cbc18ff37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denmark</value>
      <webElementGuid>01e46123-9655-4d07-8bfb-bd0b624349d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box104&quot;)</value>
      <webElementGuid>f576052c-66d1-4e1e-88bb-aeeee5219310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='box104']</value>
      <webElementGuid>5369093e-0b4a-4468-9738-c0b87c93d2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='countries']/div[4]</value>
      <webElementGuid>07284f89-94a5-4106-ba80-c04224dae001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Norway'])[1]/following::div[1]</value>
      <webElementGuid>864d954d-20d6-4807-9f45-27aedf488b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spain'])[1]/following::div[2]</value>
      <webElementGuid>3bfc96d0-9cd0-4717-82b4-2e39d6f1848c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Korea'])[1]/preceding::div[1]</value>
      <webElementGuid>abebfa2e-d695-4ad0-929f-433e185da058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweden'])[1]/preceding::div[2]</value>
      <webElementGuid>d8a7457d-f35a-4354-8a13-7c2245e017e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Denmark']/parent::*</value>
      <webElementGuid>c1909f9b-3351-459a-95d0-60ff263c7dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]</value>
      <webElementGuid>024373ea-6b74-41d1-8841-95bab6a189a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box104' and (text() = 'Denmark' or . = 'Denmark')]</value>
      <webElementGuid>294edaeb-a21d-4230-a10d-7bf4d04247e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
