<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_United States</name>
   <tag></tag>
   <elementGuidId>bdeb0498-abc7-4c23-8765-779416358fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#box103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box103&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15cdce66-8076-4839-b1c5-5d1682eaa986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box103</value>
      <webElementGuid>f3c7e7a3-33b7-459a-9f8f-d55c7b16c9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBoxRight</value>
      <webElementGuid>9667bddb-e6a1-4ecc-9dcb-97baea3a5bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>932b3bad-148e-46ff-a9c2-acade9701b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box103&quot;)</value>
      <webElementGuid>eb6bf529-6517-42ad-a813-5ad3e37c3922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='box103']</value>
      <webElementGuid>233c882f-8f56-4875-9897-c7d03288d6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='countries']/div[7]</value>
      <webElementGuid>2e257a0c-0d73-41e5-931f-608187980182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweden'])[1]/following::div[1]</value>
      <webElementGuid>f81e7282-7c2b-4eeb-adbb-74969e792cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Korea'])[1]/following::div[2]</value>
      <webElementGuid>69853957-f4a6-4502-84d0-88a91cb5e6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag And Drop scripts from DHTMLGoodies.com'])[1]/preceding::div[4]</value>
      <webElementGuid>ad36907d-8543-4460-adf2-28c2b7b23894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='United States']/parent::*</value>
      <webElementGuid>76af2bdf-b43b-4a23-a953-085d51ad291f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[7]</value>
      <webElementGuid>3a1b4db5-aa74-493d-9ca8-d806de51eeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box103' and (text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>6a37784e-66ef-4cc9-9619-09b79eac0528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
