<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Washington</name>
   <tag></tag>
   <elementGuidId>d952a75d-c7ef-4819-bd3b-d8549a6faa3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DHTMLgoodies_dragableElement2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;box3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07a227b7-8bfc-43fa-83de-b5971398abcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dragableBox</value>
      <webElementGuid>f68fe712-9d74-4fc8-b9f1-4cda2ef4f387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DHTMLgoodies_dragableElement2</value>
      <webElementGuid>903e86b1-5477-411c-a274-ff9885c99dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dragableelement</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dc1bdc34-28e6-4c32-8aa3-09c853e0fc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Washington</value>
      <webElementGuid>e9072dbc-4b57-498e-b316-ca91774c2672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DHTMLgoodies_dragableElement2&quot;)</value>
      <webElementGuid>6031694a-1766-47d2-b648-d0c539c92598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='DHTMLgoodies_dragableElement2']</value>
      <webElementGuid>0bbeedfd-c972-451e-a462-20c46ca51888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropContent']/div[5]</value>
      <webElementGuid>0684a346-9b0e-44a3-b67d-b61553dc2373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholm'])[2]/following::div[1]</value>
      <webElementGuid>f9b5f5ca-b570-443c-a5fb-4c2e91c22dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockholm'])[1]/following::div[2]</value>
      <webElementGuid>9679ef09-5d3e-4aef-bf65-ba6a54d8e31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copenhagen'])[1]/preceding::div[1]</value>
      <webElementGuid>5ac71edc-d2ef-4a9f-9c18-22aa89ce308c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copenhagen'])[2]/preceding::div[2]</value>
      <webElementGuid>d2c5b956-01fa-46df-a3bf-3f55ab622cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Washington']/parent::*</value>
      <webElementGuid>cd3502df-1db2-497b-a8e9-42512c03cc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[5]</value>
      <webElementGuid>1418492f-96bd-4af1-a1e0-c56d702e1b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'DHTMLgoodies_dragableElement2' and (text() = 'Washington' or . = 'Washington')]</value>
      <webElementGuid>02dd6d3e-a4e0-4599-9de6-eac302fd8aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
