<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SHOW-CONFIRM-BOX</name>
   <tag></tag>
   <elementGuidId>8d462ef8-d118-466d-ae9e-e3c7279188c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmexample']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jcalert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ec89ff4-9144-469b-8726-84ed8cdd7848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jcalert</value>
      <webElementGuid>ccc8ee4c-858b-4188-bbb3-1fe23a7639ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; ConfirmAlert()</value>
      <webElementGuid>ecd14793-8d38-4cf4-93fa-58a80b66ee9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Alert</value>
      <webElementGuid>5a48a4b2-92b0-4608-8b50-40e573116dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jcalert&quot;)</value>
      <webElementGuid>125b7fa8-05a4-4ca3-8bdb-0c07f5ef1209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='jcalert']</value>
      <webElementGuid>5c6db7e9-16b6-4ec8-87d6-75cd3594027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Alert'])[2]/following::button[1]</value>
      <webElementGuid>e2447e66-88fc-4185-a126-e1ac84283088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prompt Alert'])[2]/preceding::button[1]</value>
      <webElementGuid>fcd24edf-3400-4ffc-a01e-7456201fd66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>0d25954d-b0df-4eac-85c6-16821a26318c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'jcalert' and (text() = 'Confirm Alert' or . = 'Confirm Alert')]</value>
      <webElementGuid>fd63beab-c2f3-4566-9092-522dc59cd317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
