<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SHOW-ALERT-BOX</name>
   <tag></tag>
   <elementGuidId>230d4afe-6cbc-4a70-8fa2-ddff19372bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alertexamples']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jbalert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbbcda95-b152-43fe-b453-e257baa44cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jbalert</value>
      <webElementGuid>528953b0-a265-4015-9f04-7823184d5ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; newAlert()</value>
      <webElementGuid>7df4404a-5d53-4282-84fe-6cf50099a5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic Alert</value>
      <webElementGuid>a6764e09-a00d-47fa-8e09-f415c864319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jbalert&quot;)</value>
      <webElementGuid>50ce88ee-67b4-4efc-acbf-f38df165a543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='jbalert']</value>
      <webElementGuid>07157f37-2e8a-4d0e-9559-8d9163892726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prompt Alert'])[1]/following::button[1]</value>
      <webElementGuid>b8a39dfc-c59f-426f-a41d-42d8e6598d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Alert'])[2]/preceding::button[1]</value>
      <webElementGuid>a0d94173-340c-4c11-aea5-af4171018d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prompt Alert'])[2]/preceding::button[2]</value>
      <webElementGuid>0c20934d-b4da-47bd-b8ef-637436a2f67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>45e1278a-ccc9-47cf-a15b-300d68aa8c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'jbalert' and (text() = 'Basic Alert' or . = 'Basic Alert')]</value>
      <webElementGuid>034e9264-0698-4fb2-9733-fcb438f13326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
