<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SHOW-PROMPT-BOX</name>
   <tag></tag>
   <elementGuidId>148c4af2-8450-4b6b-ad47-b35995472478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promptexample']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jpalert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c29d4f22-a762-4ac1-ae86-e02d656c898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpalert</value>
      <webElementGuid>1f089418-ccbf-4838-97d9-b21d38b63611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; PromptAlert()</value>
      <webElementGuid>148284b1-e460-4d1d-b79b-9640dea51235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prompt Alert</value>
      <webElementGuid>30d92517-0123-46d2-b066-a9633a012915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpalert&quot;)</value>
      <webElementGuid>67671555-9e4d-4320-9069-250e5fba483f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='jpalert']</value>
      <webElementGuid>658ab294-0929-4d41-bc33-d8688d887a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Alert'])[2]/following::button[1]</value>
      <webElementGuid>47879b99-85a6-4eef-86d9-c3b69ea02fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Alert'])[2]/following::button[2]</value>
      <webElementGuid>31d8d106-e6ab-4163-9359-36d56a541ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[3]</value>
      <webElementGuid>f846e984-e817-41d0-89fd-abd79e7c7bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'jpalert' and (text() = 'Prompt Alert' or . = 'Prompt Alert')]</value>
      <webElementGuid>c462bd32-ee42-4de5-a951-d8a6ba976fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
