<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PASSWORD-TEXTBOX</name>
   <tag></tag>
   <elementGuidId>11531b58-cfa7-4e81-91c0-bb5b67c0bca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a151a3ee-d5a6-485b-99bc-1bc2b6563d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password *</value>
      <webElementGuid>bd848bbb-f75c-4192-b49a-82f99e7efdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input undefined</value>
      <webElementGuid>ec027a84-941e-4e40-b8fb-92b417e2e434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8732527b-759b-4660-be89-88c67f43ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>b93ca18e-f46a-47cc-86ed-78c555479e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>12f078c9-76a0-478a-af75-006579f81fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;sectionTwo styles_loginBox__DYG_V&quot;]/div[@class=&quot;wraper&quot;]/div[@class=&quot;styles_mainSec__IDj2h&quot;]/form[@class=&quot;styles_form__qmKve&quot;]/div[@class=&quot;form-group styles_formGroup__1kaxM&quot;]/div[@class=&quot;form-sec undefined undefined&quot;]/input[@class=&quot;input undefined&quot;]</value>
      <webElementGuid>e6c57a7c-524c-4a0c-8d37-c06fe44321bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>9d4ed868-8005-4440-8eb8-9306a8c139ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f8d5e50f-d6a8-4ca0-8f2c-662b2abf3e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password *' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>485cfc17-85b0-40b0-89f9-45be43c0194e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
