<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CHECKBOX_3</name>
   <tag></tag>
   <elementGuidId>338755bf-3e5f-4e47-a49d-a562d492eb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.select-initialized</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Three']//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>177bffb1-9c95-4015-b897-669691f0257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-initialized</value>
      <webElementGuid>c2c96cb4-1864-4751-a291-5d4cd0f2e58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mdb-select-initialized</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47f032c6-3726-4b13-80d0-b62fe371b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          One
          Two
          Three
          Four
          Five
          Six
          Seven
          Eight
        </value>
      <webElementGuid>cc7b66b0-3c00-4c4f-8568-656e03f281b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-wrapper-638138&quot;)/select[@class=&quot;select-initialized&quot;]</value>
      <webElementGuid>80c06255-62f9-4911-8c7b-1268712d0643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-wrapper-638138']/select</value>
      <webElementGuid>96a1140c-217e-44bc-b7de-b1d70eecefed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example label'])[1]/following::select[1]</value>
      <webElementGuid>07458df6-1ccb-44f6-83bf-e5a81b7c97b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MDBootstrap Pro'])[1]/following::select[1]</value>
      <webElementGuid>6e6d98a8-d349-4f28-a69f-be96d012eb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show code'])[1]/preceding::select[1]</value>
      <webElementGuid>6e7a5599-ebaa-4338-a54c-546000539c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit in sandbox'])[1]/preceding::select[1]</value>
      <webElementGuid>e0e1d2db-8a42-4045-8272-42fcf4931cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c09d7a8c-028b-480f-8196-706b9f99c8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
          One
          Two
          Three
          Four
          Five
          Six
          Seven
          Eight
        ' or . = '
          One
          Two
          Three
          Four
          Five
          Six
          Seven
          Eight
        ')]</value>
      <webElementGuid>3ae6675e-4e95-40b5-8d2b-abff510aaee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
