<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GENDER_MALE</name>
   <tag></tag>
   <elementGuidId>758f2059-9907-4a7b-94a0-70ef0941caeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='male']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#male</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7f5d928-d78d-4385-9ee4-eb90ba1e7c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9e865dff-347b-47a5-aafd-3b4fb28529bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>39c5c271-5763-43f6-9d88-c8d03e6719de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>5add002f-4d1d-4c16-9171-0f7be45b2829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>dc137c43-4547-4899-9d59-86a6e9a45b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;male&quot;)</value>
      <webElementGuid>05e78716-0465-443a-a9e5-b1a2eb21b56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='male']</value>
      <webElementGuid>cb80b961-a647-4d77-aed6-1be43a8dd74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/label[4]/input</value>
      <webElementGuid>03349d42-689f-4fd3-b03f-2043ed3f35ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>09c2a4e9-1b2c-4f5b-be0d-12db5622963c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'male' and @name = 'gender']</value>
      <webElementGuid>350d6022-60c2-4580-bb11-e1c97c897172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
