<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MUSIC_CHECKBOX</name>
   <tag></tag>
   <elementGuidId>361c3757-adf0-40a9-8e03-178a758d4f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='music']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#music</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa193d03-1715-4991-8763-65181fa0018d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>287e9518-17d0-403c-b991-74d9d8b39adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>music</value>
      <webElementGuid>e17484b3-0f22-4bfa-b14b-0f2fbb7a402c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hobbies</value>
      <webElementGuid>25fdff16-588a-4ba9-82a1-3c63700cc8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>music</value>
      <webElementGuid>cdb00c16-af2d-42b1-a075-7160b6cd6142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;music&quot;)</value>
      <webElementGuid>10c76364-8a5d-4059-ad93-0db1d5f2491b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='music']</value>
      <webElementGuid>f4ec8713-7941-441d-b26b-ed00fc03bd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/label[9]/input</value>
      <webElementGuid>3921ccfa-80e9-4a4f-a07b-146bd126253e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[9]/input</value>
      <webElementGuid>662be21f-f1ca-403b-ad85-e81d855f1d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'music' and @name = 'hobbies']</value>
      <webElementGuid>704bb90e-ff9b-421d-b718-596e7920b304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
