<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TRAVELLING_CHECKBOX</name>
   <tag></tag>
   <elementGuidId>73d31129-2e0a-4cb3-b154-4fcdd6e68ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='traveling']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#traveling</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a49cd3cc-a045-4ace-b7af-0f17e0e5fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>389b9541-4275-463c-828d-99e7b6cdb3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>traveling</value>
      <webElementGuid>cf1fb246-024d-45ff-aa2e-167516e283f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hobbies</value>
      <webElementGuid>632f8cfe-fe18-44f2-93a3-e7d087070e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>traveling</value>
      <webElementGuid>c50f3fa2-664a-4130-9af1-389df5c18a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;traveling&quot;)</value>
      <webElementGuid>11ba0fce-3a1d-4ab1-8569-b68b472f4240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='traveling']</value>
      <webElementGuid>2b09a5aa-3c6f-4349-917b-93a5c88e169f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/label[8]/input</value>
      <webElementGuid>1f6faf1d-9517-41f1-9efd-31feef6d0aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[8]/input</value>
      <webElementGuid>7dbdff79-ddbc-4a54-ae11-8d0f58211b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'traveling' and @name = 'hobbies']</value>
      <webElementGuid>1213cd27-b17a-4b50-bfea-2452dfe24d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
