<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ADD_COMPUTER_BUTTON</name>
   <tag></tag>
   <elementGuidId>2bf0e586-7c0b-4f7a-b4a2-315d1964343f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6321a70b-6d47-48d1-8bb9-8f015e28319b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn success</value>
      <webElementGuid>b55d1aa2-eb6f-4dc5-8eff-cd68f43ded0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>b137f77d-cf0d-477e-888c-add7d31b3a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/computers/new</value>
      <webElementGuid>d57dd7fc-d0bf-45d8-8704-5bc7437a70a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a new computer</value>
      <webElementGuid>48a3ce82-5336-44d6-8e64-08bad32a8bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add&quot;)</value>
      <webElementGuid>688f8cc7-802f-4bfc-89e2-ef34aacf9921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='add']</value>
      <webElementGuid>0e246492-5eb6-4737-8773-f4482869df05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/a</value>
      <webElementGuid>36ae050a-89f8-4311-ba99-9879f57cad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add a new computer')]</value>
      <webElementGuid>e64be52d-dde9-4532-abee-08f9cdae6f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer database'])[1]/following::a[1]</value>
      <webElementGuid>16e74da9-0ac6-43c7-8fda-e323d0d0648d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer name'])[1]/preceding::a[1]</value>
      <webElementGuid>bf719ac1-0af2-4b61-abcc-eeec790cd7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduced'])[1]/preceding::a[2]</value>
      <webElementGuid>22fba3ae-8cce-418c-914b-9806aa03bc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a new computer']/parent::*</value>
      <webElementGuid>9ac386b9-aec3-491f-87a9-fbc0db7dc8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/computers/new')]</value>
      <webElementGuid>281e1ea4-3534-442a-83cc-b7184e3d3d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>ad0f67cb-9a34-4ca3-8fa4-ab7f949fac69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'add' and @href = '/computers/new' and (text() = 'Add a new computer' or . = 'Add a new computer')]</value>
      <webElementGuid>dd73ad76-a183-4f5e-8c05-baa7ac3ea6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
