<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COMPANY_DROPDOWN</name>
   <tag></tag>
   <elementGuidId>1fcbe4bc-ac9f-4d50-b153-2d5dd78b6c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4a85266a-4e24-4228-81f8-a541f376b5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>b2a9a499-8340-4635-958b-9f8771b84e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>7ba39fa2-25dc-448c-ad8c-dbb1cdc8f9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics</value>
      <webElementGuid>e0b2c984-b1b7-4780-a954-168253df5c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>6221bb0f-4b96-42a2-8427-ed1208507d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='company']</value>
      <webElementGuid>89d77081-be43-4f16-8798-e55bf5abc610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[4]/div/select</value>
      <webElementGuid>05f3a4b8-c29d-4cee-811b-877b67c25369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>35e5c915-6de1-4fea-b9f1-faf7f1b86745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>77b36ac4-d569-4869-a5dc-505253765f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>84790177-eec4-45ff-81d9-7d5ac53992d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'company' and @name = 'company' and (text() = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics' or . = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics')]</value>
      <webElementGuid>da2be58b-9bbc-48af-a602-c29f17d04888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
