<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DELETE_THIS_COMPUTER</name>
   <tag></tag>
   <elementGuidId>e1c3b45e-bef3-4cba-b44f-c3be8f3b1b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Delete this computer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>532146f5-709b-4398-aabf-0bf5fd39e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8f412647-e6b6-4591-97ed-db4df7a9b773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete this computer</value>
      <webElementGuid>344580c1-a973-47d2-8be5-28d9407dbfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn danger</value>
      <webElementGuid>53d5fcd3-b9ea-4da6-94b5-cdfc2c5a1baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/form[@class=&quot;topRight&quot;]/input[@class=&quot;btn danger&quot;]</value>
      <webElementGuid>44e263dc-7822-4268-a4ce-5fc7eeaee8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Delete this computer']</value>
      <webElementGuid>6593ed8c-ff63-4764-840f-835176cb7398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form[2]/input</value>
      <webElementGuid>50dfbbbd-b07b-47e8-9cb5-cfade685d8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/input</value>
      <webElementGuid>8c0c6f18-569a-4fc4-b774-9b8337ed0c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>4b42d495-53bc-4176-aff3-eb09aa26125b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
