<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDIT_INTRODUCED</name>
   <tag></tag>
   <elementGuidId>680e8cfd-629e-4cc4-b9e6-7e99fcbc80e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='introduced']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#introduced</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b183b89-d4e2-49ac-b8e5-2e87b13b64c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6076238-a658-4a20-868f-b7f759480cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>817c8a83-31ad-460e-bc3a-af981301eca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>5f07b2ab-b843-41e4-ab41-4aa34a8eaf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;introduced&quot;)</value>
      <webElementGuid>86cd32c1-08d2-4109-9945-1826d4a61e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='introduced']</value>
      <webElementGuid>3ca72654-2530-43d6-a46e-a0f95b07bc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[2]/div/input</value>
      <webElementGuid>f88dae1c-f93a-47f7-a0e9-0ff00966d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d38a6743-2d93-4030-97c3-4e30e041c379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'introduced' and @name = 'introduced']</value>
      <webElementGuid>629f1b17-1cb7-4319-a978-e1ab7c89e1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
