<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDIT_DROPDOWN</name>
   <tag></tag>
   <elementGuidId>2bb86c17-baee-487b-87a8-ab4c3cd46a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18aa175b-dbf9-486c-97c2-d5b9f45efb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>cc466657-8242-47d0-98e0-39944447a872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>9234d530-c3fc-4f16-a83f-b949e91317cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics</value>
      <webElementGuid>efed25b6-42a7-42e1-bdcb-5f8dbc90389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>a1f551f2-7577-42c6-a5c5-3bc02dd81b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='company']</value>
      <webElementGuid>ad99e40e-6512-459f-9613-2eab9d1b30b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[4]/div/select</value>
      <webElementGuid>152c8fac-4e2c-4311-9185-a646c6b97cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>9f7ee68b-4a09-4288-adef-6eff279502c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>2e9f21b1-d019-4278-ade8-282fe5553d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b558cb07-b3ee-4b6a-bbb3-b5ce1549104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'company' and @name = 'company' and (text() = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics' or . = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics')]</value>
      <webElementGuid>3b7dbeb9-63c4-47f3-a64a-3b780326add7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
