<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH_TEXTBOX</name>
   <tag></tag>
   <elementGuidId>f6da4406-765d-46c8-a430-ec27acd75552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2daa999e-e732-4492-b5da-3694695786a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6989f73d-55a2-4ed5-88fa-fe78af682de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>698c6d1e-9f2e-42f1-a8fd-c5b7e7b21e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>3167b5b7-90e3-40cb-86c1-4fb79929c098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter by computer name...</value>
      <webElementGuid>2bb7a052-f7a6-4073-b71d-0e4099e5d319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>84d5e8bc-2c0c-4c6e-9079-44f2d43e4c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbox&quot;)</value>
      <webElementGuid>f90497a8-6d83-460a-be04-778cf9f52852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchbox']</value>
      <webElementGuid>7de70ce8-0be2-4fd3-8f4c-03e26373f4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/input</value>
      <webElementGuid>000392f0-1b42-48a7-8726-5efdfc159e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d255adca-8fb0-4162-92a2-bbc65d05cbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'searchbox' and @name = 'f' and @placeholder = 'Filter by computer name...']</value>
      <webElementGuid>441944b3-dcce-40da-a713-2db4f8da5e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
